-- Author: caochuncheng2002@gmail.com
-- Created: 2015-09-24
-- Description: proto lua config
-- This file is generated by script tool,Do not edit it.


-- Data Type Id Description:
--     1:bool
--     2:int64
--     3:int32
--     4:int16
--     5:byte
--     6:double
--     7:string
--     自定义结构从100开始标记类型
--     所有类型的数组结构1000+id


local toc_defines={
    -- m_auth_key_toc
    -- Feilds={op_code,server_time,is_create_role,role_info,map_id,attr_list,quick_key}
    -- m_auth_key_toc={{optional,int32},{optional,int64},{optional,bool},{optional,p_role},{optional,int16},{repeated,p_attr},{required,string}}
    [101]={3,"op_code",2,"server_time",1,"is_create_role",114,"role_info",4,"map_id",1108,"attr_list",7,"quick_key"},

    -- m_auth_quick_toc
    -- Feilds={op_code,server_time,role_info,map_id,attr_list,quick_key}
    -- m_auth_quick_toc={{optional,int32},{optional,int64},{optional,p_role},{optional,int16},{repeated,p_attr},{required,string}}
    [102]={3,"op_code",2,"server_time",114,"role_info",4,"map_id",1108,"attr_list",7,"quick_key"},

    -- m_role_create_toc
    -- Feilds={op_code,op_reason}
    -- m_role_create_toc={{optional,int32},{optional,string}}
    [801]={3,"op_code",7,"op_reason"},

    -- m_role_online_info_toc
    -- Feilds={channel_list}
    -- m_role_online_info_toc={{repeated,byte}}
    [802]={1005,"channel_list"},

    -- m_map_enter_toc
    -- Feilds={op_code,op_reason,pos,map_id}
    -- m_map_enter_toc={{optional,int32},{optional,string},{optional,p_pos},{optional,int16}}
    [201]={3,"op_code",7,"op_reason",105,"pos",4,"map_id"},

    -- m_map_slice_enter_toc
    -- Feilds={roles,del_roles,pets,del_pets,monsters,del_monsters,avatars,del_avatars}
    -- m_map_slice_enter_toc={{repeated,p_map_role},{repeated,int64},{repeated,p_map_pet},{repeated,int64},{repeated,p_map_monster},{repeated,int32},{repeated,p_map_avatar},{repeated,int32}}
    [205]={1117,"roles",1002,"del_roles",1126,"pets",1002,"del_pets",1127,"monsters",1003,"del_monsters",1129,"avatars",1003,"del_avatars"},

    -- m_map_update_mapinfo_toc
    -- Feilds={actor_id,actor_type,role_info}
    -- m_map_update_mapinfo_toc={{required,int64},{required,byte},{optional,p_map_role}}
    [203]={2,"actor_id",5,"actor_type",117,"role_info"},

    -- m_map_actor_dead_toc
    -- Feilds={actor_id,actor_type,killer_id,killer_type}
    -- m_map_actor_dead_toc={{required,int64},{required,byte},{required,int64},{required,byte}}
    [208]={2,"actor_id",5,"actor_type",2,"killer_id",5,"killer_type"},

    -- m_map_slice_quit_toc
    -- Feilds={actor_type,del_ids}
    -- m_map_slice_quit_toc={{required,byte},{repeated,int64}}
    [209]={5,"actor_type",1002,"del_ids"},

    -- m_map_quit_toc
    -- Feilds={role_id}
    -- m_map_quit_toc={{required,int64}}
    [202]={2,"role_id"},

    -- m_map_query_toc
    -- Feilds={op_type,actor_type,op_code,roles,pets,monsters}
    -- m_map_query_toc={{required,byte},{required,byte},{required,int32},{repeated,p_map_role},{repeated,p_map_pet},{repeated,p_map_monster}}
    [206]={5,"op_type",5,"actor_type",3,"op_code",1117,"roles",1126,"pets",1127,"monsters"},

    -- m_map_change_map_toc
    -- Feilds={op_code,map_id,x,y}
    -- m_map_change_map_toc={{required,int32},{optional,int16},{optional,int32},{optional,int32}}
    [204]={3,"op_code",4,"map_id",3,"x",3,"y"},

    -- m_move_walk_path_toc
    -- Feilds={op_code,move_id,pos}
    -- m_move_walk_path_toc={{optional,int32},{required,int64},{required,p_pos}}
    [301]={3,"op_code",2,"move_id",105,"pos"},

    -- m_move_sync_toc
    -- Feilds={move_id,pos}
    -- m_move_sync_toc={{required,int64},{required,p_pos}}
    [303]={2,"move_id",105,"pos"},

    -- m_system_heartbeat_toc
    -- Feilds={time,server_time}
    -- m_system_heartbeat_toc={{required,int64},{required,int64}}
    [401]={2,"time",2,"server_time"},

    -- m_system_error_toc
    -- Feilds={error_no,error_info}
    -- m_system_error_toc={{required,int32},{required,string}}
    [403]={3,"error_no",7,"error_info"},

    -- m_system_message_toc
    -- Feilds={op_code,op_reason}
    -- m_system_message_toc={{required,int32},{required,string}}
    [402]={3,"op_code",7,"op_reason"},

    -- m_system_fcm_toc
    -- Feilds={info,remain_time,total_time}
    -- m_system_fcm_toc={{required,string},{required,int32},{required,int32}}
    [404]={7,"info",3,"remain_time",3,"total_time"},

    -- m_system_need_fcm_toc
    -- Feilds={remain_time}
    -- m_system_need_fcm_toc={{required,int32}}
    [406]={3,"remain_time"},

    -- m_system_set_fcm_toc
    -- Feilds={succ,reason}
    -- m_system_set_fcm_toc={{required,bool},{optional,string}}
    [405]={1,"succ",7,"reason"},

    -- m_system_config_update_toc
    -- Feilds={err_code,config_list}
    -- m_system_config_update_toc={{optional,int32},{repeated,p_key_value}}
    [407]={3,"err_code",1100,"config_list"},

    -- m_goods_query_toc
    -- Feilds={op_type,role_id,bag_id,goods_id,op_code,goods_list,grid_number}
    -- m_goods_query_toc={{required,byte},{optional,int64},{optional,byte},{optional,int64},{required,int32},{repeated,p_goods},{optional,int16}}
    [701]={5,"op_type",2,"role_id",5,"bag_id",2,"goods_id",3,"op_code",1131,"goods_list",4,"grid_number"},

    -- m_goods_swap_toc
    -- Feilds={op_code,goods_id,src_bag_id,bag_position,bag_id,goods_1,goods_2}
    -- m_goods_swap_toc={{required,int32},{required,int64},{required,byte},{required,int16},{required,byte},{optional,p_goods},{optional,p_goods}}
    [702]={3,"op_code",2,"goods_id",5,"src_bag_id",4,"bag_position",5,"bag_id",131,"goods_1",131,"goods_2"},

    -- m_goods_tidy_toc
    -- Feilds={op_code,bag_id,goods_list}
    -- m_goods_tidy_toc={{required,int32},{required,byte},{repeated,p_goods}}
    [706]={3,"op_code",5,"bag_id",1131,"goods_list"},

    -- m_goods_divide_toc
    -- Feilds={goods_id,number,bag_position,bag_id,op_code,goods_1,goods_2}
    -- m_goods_divide_toc={{required,int64},{required,int16},{required,int16},{required,byte},{required,int32},{optional,p_goods},{optional,p_goods}}
    [704]={2,"goods_id",4,"number",4,"bag_position",5,"bag_id",3,"op_code",131,"goods_1",131,"goods_2"},

    -- m_goods_destroy_toc
    -- Feilds={op_type,bag_id,goods_id,op_code}
    -- m_goods_destroy_toc={{required,byte},{required,byte},{repeated,int64},{required,int32}}
    [703]={5,"op_type",5,"bag_id",1002,"goods_id",3,"op_code"},

    -- m_goods_update_toc
    -- Feilds={bag_id,goods_list,del_id_list}
    -- m_goods_update_toc={{optional,byte},{repeated,p_goods},{repeated,int64}}
    [705]={5,"bag_id",1131,"goods_list",1002,"del_id_list"},

    -- m_goods_show_toc
    -- Feilds={op_code}
    -- m_goods_show_toc={{required,int32}}
    [707]={3,"op_code"},

    -- m_goods_use_toc
    -- Feilds={op_type,goods_id,use_num,target_id,op_code,op_reason,goods_number}
    -- m_goods_use_toc={{required,byte},{required,int64},{required,int16},{required,int64},{required,int32},{optional,string},{optional,int16}}
    [708]={5,"op_type",2,"goods_id",4,"use_num",2,"target_id",3,"op_code",7,"op_reason",4,"goods_number"},

    -- m_goods_add_grid_toc
    -- Feilds={op_type,bag_id,add_grid,op_code,grid_number}
    -- m_goods_add_grid_toc={{required,byte},{required,byte},{required,int16},{required,int32},{required,int16}}
    [709]={5,"op_type",5,"bag_id",4,"add_grid",3,"op_code",4,"grid_number"},

    -- m_role_attr_change_toc
    -- Feilds={op_type,attr_list}
    -- m_role_attr_change_toc={{required,byte},{repeated,p_attr}}
    [803]={5,"op_type",1108,"attr_list"},

    -- m_role_get_info_toc
    -- Feilds={op_type,id,op_code,role_info}
    -- m_role_get_info_toc={{required,byte},{required,int64},{optional,int32},{optional,p_role_info}}
    [806]={5,"op_type",2,"id",3,"op_code",109,"role_info"},

    -- m_role_get_skill_toc
    -- Feilds={role_skill}
    -- m_role_get_skill_toc={{repeated,p_role_skill}}
    [809]={1146,"role_skill"},

    -- m_role_relive_toc
    -- Feilds={op_code,role_id,hp}
    -- m_role_relive_toc={{required,int32},{optional,int64},{optional,int32}}
    [810]={3,"op_code",2,"role_id",3,"hp"},

    -- m_role_set_toc
    -- Feilds={op_type,attr_list,op_code}
    -- m_role_set_toc={{required,byte},{repeated,p_attr},{optional,int32}}
    [807]={5,"op_type",1108,"attr_list",3,"op_code"},

    -- m_role_cure_toc
    -- Feilds={op_code}
    -- m_role_cure_toc={{required,int32}}
    [811]={3,"op_code"},

    -- m_pet_query_toc
    -- Feilds={op_type,op_code,pets,pet_info,role_pet}
    -- m_pet_query_toc={{required,byte},{required,int32},{repeated,p_pet_tiny},{optional,p_pet},{optional,p_role_pet}}
    [1501]={5,"op_type",3,"op_code",1124,"pets",125,"pet_info",123,"role_pet"},

    -- m_pet_battle_toc
    -- Feilds={op_code,pet_id,pet_info}
    -- m_pet_battle_toc={{required,int32},{optional,int64},{optional,p_pet}}
    [1502]={3,"op_code",2,"pet_id",125,"pet_info"},

    -- m_pet_back_toc
    -- Feilds={op_code}
    -- m_pet_back_toc={{required,int32}}
    [1503]={3,"op_code"},

    -- m_pet_free_toc
    -- Feilds={op_code}
    -- m_pet_free_toc={{required,int32}}
    [1504]={3,"op_code"},

    -- m_fight_chant_toc
    -- Feilds={actor_id,actor_type,skill_id,state,effect_pos}
    -- m_fight_chant_toc={{required,int64},{required,byte},{required,int32},{required,byte},{repeated,p_pos}}
    [1402]={2,"actor_id",5,"actor_type",3,"skill_id",5,"state",1105,"effect_pos"},

    -- m_fight_action_toc
    -- Feilds={actor_id,actor_type,skill_id,target_pos,state,effect_pos}
    -- m_fight_action_toc={{required,int64},{required,byte},{required,int32},{required,p_pos},{required,byte},{repeated,p_pos}}
    [1403]={2,"actor_id",5,"actor_type",3,"skill_id",105,"target_pos",5,"state",1105,"effect_pos"},

    -- m_fight_attack_toc
    -- Feilds={op_code,skill_id,level,step,src_id,src_type,target_id,target_type,target_pos,result_type,result}
    -- m_fight_attack_toc={{required,int32},{required,int32},{required,int16},{required,byte},{required,int64},{required,byte},{required,int64},{required,byte},{optional,p_pos},{required,byte},{repeated,p_attack_result}}
    [1401]={3,"op_code",3,"skill_id",4,"level",5,"step",2,"src_id",5,"src_type",2,"target_id",5,"target_type",105,"target_pos",5,"result_type",1118,"result"},

    -- m_fight_buff_toc
    -- Feilds={actor_id,actor_type,cur_hp,result_buff}
    -- m_fight_buff_toc={{required,int64},{optional,byte},{optional,int32},{repeated,p_attack_result_buff}}
    [1404]={2,"actor_id",5,"actor_type",3,"cur_hp",1120,"result_buff"},

    -- m_buff_add_toc
    -- Feilds={object_id,object_type,buffs}
    -- m_buff_add_toc={{required,int64},{required,byte},{repeated,p_actor_buff}}
    [1701]={2,"object_id",5,"object_type",1122,"buffs"},

    -- m_buff_update_toc
    -- Feilds={object_id,object_type,buffs}
    -- m_buff_update_toc={{required,int64},{required,byte},{repeated,p_actor_buff}}
    [1702]={2,"object_id",5,"object_type",1122,"buffs"},

    -- m_buff_del_toc
    -- Feilds={object_id,object_type,buff_ids}
    -- m_buff_del_toc={{required,int64},{required,byte},{repeated,int32}}
    [1703]={2,"object_id",5,"object_type",1003,"buff_ids"},

    -- m_letter_get_toc
    -- Feilds={letters}
    -- m_letter_get_toc={{repeated,p_letter_simple_info}}
    [902]={1135,"letters"},

    -- m_letter_open_toc
    -- Feilds={op_code,op_reason,result}
    -- m_letter_open_toc={{optional,int32},{optional,string},{optional,p_letter_info}}
    [903]={3,"op_code",7,"op_reason",134,"result"},

    -- m_letter_send_toc
    -- Feilds={op_code,op_reason,letter}
    -- m_letter_send_toc={{optional,int32},{optional,string},{optional,p_letter_simple_info}}
    [906]={3,"op_code",7,"op_reason",135,"letter"},

    -- m_letter_delete_toc
    -- Feilds={op_code,op_reason,letter_ids}
    -- m_letter_delete_toc={{optional,int32},{optional,string},{repeated,int32}}
    [904]={3,"op_code",7,"op_reason",1003,"letter_ids"},

    -- m_letter_accept_goods_toc
    -- Feilds={op_code,op_reason,letter_id,goods_id,goods_num}
    -- m_letter_accept_goods_toc={{optional,int32},{optional,string},{required,int32},{required,int64},{required,int16}}
    [905]={3,"op_code",7,"op_reason",3,"letter_id",2,"goods_id",4,"goods_num"},

    -- m_mission_query_toc
    -- Feilds={op_type,id_list,op_code,op_reason,mission_list}
    -- m_mission_query_toc={{required,byte},{repeated,int32},{required,int32},{optional,string},{repeated,p_mission_info}}
    [1001]={5,"op_type",1003,"id_list",3,"op_code",7,"op_reason",1136,"mission_list"},

    -- m_mission_do_toc
    -- Feilds={op_type,id,npc_id,prop_choose,op_code,op_reason,current_status,current_model_status,mission_reward}
    -- m_mission_do_toc={{required,byte},{required,int32},{required,int32},{repeated,int32},{required,int32},{optional,string},{optional,int32},{optional,int32},{optional,p_mission_reward}}
    [1002]={5,"op_type",3,"id",3,"npc_id",1003,"prop_choose",3,"op_code",7,"op_reason",3,"current_status",3,"current_model_status",138,"mission_reward"},

    -- m_mission_do_complete_toc
    -- Feilds={id,op_code,op_fee_type,op_fee}
    -- m_mission_do_complete_toc={{required,int32},{required,int32},{optional,int32},{optional,int32}}
    [1005]={3,"id",3,"op_code",3,"op_fee_type",3,"op_fee"},

    -- m_mission_do_submit_toc
    -- Feilds={big_group,do_times,op_code,op_fee_type,op_fee}
    -- m_mission_do_submit_toc={{required,int32},{required,int16},{required,int32},{optional,byte},{optional,int32}}
    [1006]={3,"big_group",4,"do_times",3,"op_code",5,"op_fee_type",3,"op_fee"},

    -- m_mission_cancel_toc
    -- Feilds={id,op_code,op_reason}
    -- m_mission_cancel_toc={{required,int32},{required,int32},{optional,string}}
    [1003]={3,"id",3,"op_code",7,"op_reason"},

    -- m_mission_update_toc
    -- Feilds={del_list,update_list}
    -- m_mission_update_toc={{repeated,int32},{repeated,p_mission_info}}
    [1004]={1003,"del_list",1136,"update_list"},

    -- m_mission_recolor_toc
    -- Feilds={op_type,mission_id,to_color,op_code,new_color,coin_tims,last_coin_time,op_fee}
    -- m_mission_recolor_toc={{required,byte},{required,int32},{optional,byte},{optional,int32},{optional,byte},{optional,int32},{optional,int32},{optional,int32}}
    [1007]={5,"op_type",3,"mission_id",5,"to_color",3,"op_code",5,"new_color",3,"coin_tims",3,"last_coin_time",3,"op_fee"},

    -- m_mission_auto_toc
    -- Feilds={op_type,big_group,loop_times,op_code,auto_list,auto_info,mission_reward}
    -- m_mission_auto_toc={{required,byte},{optional,int32},{optional,int16},{optional,int32},{repeated,p_mission_auto},{optional,p_mission_auto},{optional,p_mission_reward}}
    [1008]={5,"op_type",3,"big_group",4,"loop_times",3,"op_code",1139,"auto_list",139,"auto_info",138,"mission_reward"},

    -- m_role_add_exp_toc
    -- Feilds={op_code,role_id,add_exp_type,add_exp,old_level,new_level}
    -- m_role_add_exp_toc={{optional,int32},{optional,int64},{optional,byte},{optional,int64},{optional,int16},{optional,int16}}
    [804]={3,"op_code",2,"role_id",5,"add_exp_type",2,"add_exp",4,"old_level",4,"new_level"},

    -- m_role_level_up_toc
    -- Feilds={op_code,role_id,add_exp_type,add_exp,old_level,new_level}
    -- m_role_level_up_toc={{optional,int32},{optional,int64},{optional,byte},{optional,int64},{optional,int16},{optional,int16}}
    [805]={3,"op_code",2,"role_id",5,"add_exp_type",2,"add_exp",4,"old_level",4,"new_level"},

    -- m_customer_service_query_toc
    -- Feilds={op_type,id,op_code,data_list}
    -- m_customer_service_query_toc={{required,byte},{required,int32},{optional,int32},{repeated,p_customer_service}}
    [1101]={5,"op_type",3,"id",3,"op_code",1140,"data_list"},

    -- m_customer_service_do_toc
    -- Feilds={op_type,type,id,op_code,new_id}
    -- m_customer_service_do_toc={{required,byte},{required,byte},{optional,int32},{optional,int32},{optional,int32}}
    [1102]={5,"op_type",5,"type",3,"id",3,"op_code",3,"new_id"},

    -- m_customer_service_update_toc
    -- Feilds={op_type,info}
    -- m_customer_service_update_toc={{required,byte},{required,p_customer_service}}
    [1103]={5,"op_type",140,"info"},

    -- m_customer_service_del_toc
    -- Feilds={op_type,id,del_ids,op_code}
    -- m_customer_service_del_toc={{required,byte},{optional,int32},{repeated,int32},{optional,int32}}
    [1104]={5,"op_type",3,"id",1003,"del_ids",3,"op_code"},

    -- m_family_query_toc
    -- Feilds={op_type,op_from,page_id,total_page,faction_id,op_code,family_list}
    -- m_family_query_toc={{required,byte},{required,byte},{required,int16},{optional,int16},{optional,byte},{optional,int32},{repeated,p_family_list}}
    [1201]={5,"op_type",5,"op_from",4,"page_id",4,"total_page",5,"faction_id",3,"op_code",1144,"family_list"},

    -- m_family_get_toc
    -- Feilds={op_type,family_id,op_code,family_info}
    -- m_family_get_toc={{required,byte},{optional,int64},{optional,int32},{optional,p_family}}
    [1213]={5,"op_type",2,"family_id",3,"op_code",141,"family_info"},

    -- m_family_create_toc
    -- Feilds={op_type,family_name,is_friend_invite,op_code,family_info}
    -- m_family_create_toc={{required,byte},{required,string},{required,byte},{optional,int32},{optional,p_family}}
    [1202]={5,"op_type",7,"family_name",5,"is_friend_invite",3,"op_code",141,"family_info"},

    -- m_family_request_toc
    -- Feilds={family_id,op_code,role_id,request_info,del_ids}
    -- m_family_request_toc={{required,int64},{optional,int32},{optional,int64},{optional,p_family_request},{repeated,int64}}
    [1203]={2,"family_id",3,"op_code",2,"role_id",143,"request_info",1002,"del_ids"},

    -- m_family_invite_toc
    -- Feilds={op_type,invited_role_id,family_id,op_code,family_name,src_role_id,src_role_name}
    -- m_family_invite_toc={{required,byte},{required,int64},{optional,int64},{optional,int32},{optional,string},{optional,int64},{optional,string}}
    [1204]={5,"op_type",2,"invited_role_id",2,"family_id",3,"op_code",7,"family_name",2,"src_role_id",7,"src_role_name"},

    -- m_family_accept_toc
    -- Feilds={op_type,role_id,op_code,family_id,member_list,attr_list,del_ids}
    -- m_family_accept_toc={{required,byte},{required,int64},{optional,int32},{optional,int64},{repeated,p_family_member},{repeated,p_attr},{repeated,int64}}
    [1205]={5,"op_type",2,"role_id",3,"op_code",2,"family_id",1142,"member_list",1108,"attr_list",1002,"del_ids"},

    -- m_family_refuse_toc
    -- Feilds={op_type,role_id,op_code,del_ids}
    -- m_family_refuse_toc={{required,byte},{optional,int64},{optional,int32},{repeated,int64}}
    [1206]={5,"op_type",2,"role_id",3,"op_code",1002,"del_ids"},

    -- m_family_disband_toc
    -- Feilds={op_code}
    -- m_family_disband_toc={{optional,int32}}
    [1207]={3,"op_code"},

    -- m_family_fire_toc
    -- Feilds={role_id,op_code,role_name,attr_list}
    -- m_family_fire_toc={{required,int64},{required,int32},{optional,string},{repeated,p_attr}}
    [1208]={2,"role_id",3,"op_code",7,"role_name",1108,"attr_list"},

    -- m_family_leave_toc
    -- Feilds={op_code,role_id,role_name,attr_list}
    -- m_family_leave_toc={{required,int32},{optional,int64},{optional,string},{repeated,p_attr}}
    [1209]={3,"op_code",2,"role_id",7,"role_name",1108,"attr_list"},

    -- m_family_attr_change_toc
    -- Feilds={op_type,family_id,role_id,attr_list}
    -- m_family_attr_change_toc={{required,byte},{required,int64},{required,int64},{repeated,p_attr}}
    [1210]={5,"op_type",2,"family_id",2,"role_id",1108,"attr_list"},

    -- m_family_set_toc
    -- Feilds={op_type,family_id,role_id,op_code}
    -- m_family_set_toc={{required,byte},{optional,int64},{optional,int64},{required,int32}}
    [1211]={5,"op_type",2,"family_id",2,"role_id",3,"op_code"},

    -- m_family_turn_toc
    -- Feilds={role_id,op_code,role_name,attr_list}
    -- m_family_turn_toc={{required,int64},{required,int32},{optional,string},{repeated,p_attr}}
    [1212]={2,"role_id",3,"op_code",7,"role_name",1108,"attr_list"},

    -- m_ranking_get_toc
    -- Feilds={rank_id,rows}
    -- m_ranking_get_toc={{required,int32},{repeated,p_rank_row}}
    [1301]={3,"rank_id",1145,"rows"},

    -- m_fb_enter_toc
    -- Feilds={op_code,fb_id,fb_times}
    -- m_fb_enter_toc={{required,int32},{optional,int16},{optional,int16}}
    [1601]={3,"op_code",4,"fb_id",4,"fb_times"},

    -- m_fb_quit_toc
    -- Feilds={op_code}
    -- m_fb_quit_toc={{required,int32}}
    [1602]={3,"op_code"},

    -- m_fb_done_toc
    -- Feilds={fb_id,status,countdown}
    -- m_fb_done_toc={{required,int16},{optional,byte},{optional,byte}}
    [1606]={4,"fb_id",5,"status",5,"countdown"},

    -- m_fb_query_toc
    -- Feilds={op_code,fbs}
    -- m_fb_query_toc={{required,int32},{repeated,p_fb}}
    [1603]={3,"op_code",1147,"fbs"},

    -- m_fb_update_toc
    -- Feilds={fbs}
    -- m_fb_update_toc={{repeated,p_fb}}
    [1604]={1147,"fbs"},

    -- m_fb_monster_toc
    -- Feilds={op_code,status,pos_list}
    -- m_fb_monster_toc={{required,int32},{optional,byte},{repeated,p_pos}}
    [1605]={3,"op_code",5,"status",1105,"pos_list"},

    -- m_chat_get_goods_toc
    -- Feilds={op_code,goods}
    -- m_chat_get_goods_toc={{required,int32},{optional,p_goods}}
    [504]={3,"op_code",131,"goods"},

    -- m_chat_join_channel_toc
    -- Feilds={channel_type}
    -- m_chat_join_channel_toc={{required,byte}}
    [503]={5,"channel_type"},

    -- m_chat_leave_channel_toc
    -- Feilds={channel_type}
    -- m_chat_leave_channel_toc={{required,byte}}
    [502]={5,"channel_type"},

    -- m_chat_in_channel_toc
    -- Feilds={channel_type,msg,msg_code,role_info,ts,err_code,msg_type}
    -- m_chat_in_channel_toc={{optional,byte},{optional,string},{optional,int32},{optional,p_chat_role},{optional,int32},{optional,int32},{optional,byte}}
    [501]={5,"channel_type",7,"msg",3,"msg_code",102,"role_info",3,"ts",3,"err_code",5,"msg_type"},

    -- m_broadcast_general_toc
    -- Feilds={type,sub_type,msg}
    -- m_broadcast_general_toc={{required,byte},{required,byte},{required,string}}
    [601]={5,"type",5,"sub_type",7,"msg"},

    -- m_team_create_toc
    -- Feilds={op_code,team_id,auto_id}
    -- m_team_create_toc={{required,int32},{optional,int32},{optional,int16}}
    [1801]={3,"op_code",3,"team_id",4,"auto_id"},

    -- m_team_invite_toc
    -- Feilds={op_code}
    -- m_team_invite_toc={{required,int32}}
    [1802]={3,"op_code"},

    -- m_team_apply_toc
    -- Feilds={op_code}
    -- m_team_apply_toc={{required,int32}}
    [1803]={3,"op_code"},

    -- m_team_accept_toc
    -- Feilds={op_code}
    -- m_team_accept_toc={{required,int32}}
    [1804]={3,"op_code"},

    -- m_team_leave_toc
    -- Feilds={op_code}
    -- m_team_leave_toc={{required,int32}}
    [1806]={3,"op_code"},

    -- m_team_kick_toc
    -- Feilds={op_code}
    -- m_team_kick_toc={{required,int32}}
    [1807]={3,"op_code"},

    -- m_team_disband_toc
    -- Feilds={op_code}
    -- m_team_disband_toc={{required,int32}}
    [1808]={3,"op_code"},

    -- m_team_appoint_toc
    -- Feilds={op_code}
    -- m_team_appoint_toc={{required,int32}}
    [1809]={3,"op_code"},

    -- m_team_sync_toc
    -- Feilds={type,team_list,auto_id}
    -- m_team_sync_toc={{required,byte},{repeated,p_team_member},{optional,int16}}
    [1810]={5,"type",1148,"team_list",4,"auto_id"}
}

return toc_defines