-- Author: caochuncheng2002@gmail.com
-- Created: 2015-09-24
-- Description: proto lua config
-- This file is generated by script tool,Do not edit it.


-- Data Type Id Description:
--     1:bool
--     2:int64
--     3:int32
--     4:int16
--     5:byte
--     6:double
--     7:string
--     自定义结构从100开始标记类型
--     所有类型的数组结构1000+id


local tos_defines={
    -- m_auth_key_tos
    -- Feilds={account_name,account_via,role_id,key,time,fcm,server_id,device_id}
    -- m_auth_key_tos={{required,string},{required,string},{required,int64},{required,string},{required,int32},{required,byte},{required,int16},{optional,string}}
    [101]={7,"account_name",7,"account_via",2,"role_id",7,"key",3,"time",5,"fcm",4,"server_id",7,"device_id"},

    -- m_auth_quick_tos
    -- Feilds={account_name,account_via,role_id,fcm,server_id,quick_key,device_id}
    -- m_auth_quick_tos={{required,string},{required,string},{required,int64},{required,byte},{required,int16},{required,string},{optional,string}}
    [102]={7,"account_name",7,"account_via",2,"role_id",5,"fcm",4,"server_id",7,"quick_key",7,"device_id"},

    -- m_role_create_tos
    -- Feilds={role_name,account_via,account_type,sex,fashion_id,faction_id,category,server_id}
    -- m_role_create_tos={{required,string},{required,string},{required,int16},{required,byte},{required,int32},{required,byte},{required,byte},{required,int16}}
    [801]={7,"role_name",7,"account_via",4,"account_type",5,"sex",3,"fashion_id",5,"faction_id",5,"category",4,"server_id"},

    -- m_map_enter_tos
    -- Feilds={map_id}
    -- m_map_enter_tos={{required,int16}}
    [201]={4,"map_id"},

    -- m_map_enter_confirm_tos
    -- Feilds={}
    -- m_map_enter_confirm_tos={}
    [207]={},

    -- m_map_update_mapinfo_tos
    -- Feilds={actor_id,actor_type,map_id}
    -- m_map_update_mapinfo_tos={{required,int64},{required,byte},{required,int16}}
    [203]={2,"actor_id",5,"actor_type",4,"map_id"},

    -- m_map_query_tos
    -- Feilds={op_type,actor_type}
    -- m_map_query_tos={{required,byte},{required,byte}}
    [206]={5,"op_type",5,"actor_type"},

    -- m_map_change_map_tos
    -- Feilds={map_id}
    -- m_map_change_map_tos={{required,int16}}
    [204]={4,"map_id"},

    -- m_move_walk_path_tos
    -- Feilds={actor_type,pos}
    -- m_move_walk_path_tos={{required,byte},{required,p_pos}}
    [301]={5,"actor_type",105,"pos"},

    -- m_move_walk_tos
    -- Feilds={actor_type,op_type,pos}
    -- m_move_walk_tos={{required,byte},{required,byte},{required,p_pos}}
    [302]={5,"actor_type",5,"op_type",105,"pos"},

    -- m_move_sync_tos
    -- Feilds={actor_type,actor_id,pos}
    -- m_move_sync_tos={{required,byte},{required,int64},{required,p_pos}}
    [303]={5,"actor_type",2,"actor_id",105,"pos"},

    -- m_system_heartbeat_tos
    -- Feilds={time}
    -- m_system_heartbeat_tos={{required,int64}}
    [401]={2,"time"},

    -- m_system_set_fcm_tos
    -- Feilds={name,card}
    -- m_system_set_fcm_tos={{required,string},{required,string}}
    [405]={7,"name",7,"card"},

    -- m_system_gm_tos
    -- Feilds={code}
    -- m_system_gm_tos={{required,string}}
    [408]={7,"code"},

    -- m_system_config_update_tos
    -- Feilds={config_list}
    -- m_system_config_update_tos={{repeated,p_key_value}}
    [407]={1100,"config_list"},

    -- m_goods_query_tos
    -- Feilds={op_type,role_id,bag_id,goods_id}
    -- m_goods_query_tos={{required,byte},{optional,int64},{optional,byte},{optional,int64}}
    [701]={5,"op_type",2,"role_id",5,"bag_id",2,"goods_id"},

    -- m_goods_swap_tos
    -- Feilds={goods_id,src_bag_id,bag_position,bag_id}
    -- m_goods_swap_tos={{required,int64},{required,byte},{required,int16},{required,byte}}
    [702]={2,"goods_id",5,"src_bag_id",4,"bag_position",5,"bag_id"},

    -- m_goods_tidy_tos
    -- Feilds={bag_id}
    -- m_goods_tidy_tos={{required,byte}}
    [706]={5,"bag_id"},

    -- m_goods_divide_tos
    -- Feilds={goods_id,number,bag_position,bag_id}
    -- m_goods_divide_tos={{required,int64},{required,int16},{required,int16},{required,byte}}
    [704]={2,"goods_id",4,"number",4,"bag_position",5,"bag_id"},

    -- m_goods_destroy_tos
    -- Feilds={op_type,goods_id,bag_id}
    -- m_goods_destroy_tos={{required,byte},{repeated,int64},{optional,byte}}
    [703]={5,"op_type",1002,"goods_id",5,"bag_id"},

    -- m_goods_show_tos
    -- Feilds={channel_type,to_role_name,show_type,goods_id,to_role_id}
    -- m_goods_show_tos={{optional,byte},{optional,string},{optional,byte},{required,int64},{optional,int64}}
    [707]={5,"channel_type",7,"to_role_name",5,"show_type",2,"goods_id",2,"to_role_id"},

    -- m_goods_use_tos
    -- Feilds={op_type,goods_id,use_num,target_id}
    -- m_goods_use_tos={{required,byte},{required,int64},{required,int16},{required,int64}}
    [708]={5,"op_type",2,"goods_id",4,"use_num",2,"target_id"},

    -- m_goods_add_grid_tos
    -- Feilds={op_type,bag_id,add_grid}
    -- m_goods_add_grid_tos={{required,byte},{required,byte},{required,int16}}
    [709]={5,"op_type",5,"bag_id",4,"add_grid"},

    -- m_role_get_info_tos
    -- Feilds={op_type,id}
    -- m_role_get_info_tos={{required,byte},{required,int64}}
    [806]={5,"op_type",2,"id"},

    -- m_role_get_skill_tos
    -- Feilds={}
    -- m_role_get_skill_tos={}
    [809]={},

    -- m_role_relive_tos
    -- Feilds={type}
    -- m_role_relive_tos={{required,byte}}
    [810]={5,"type"},

    -- m_role_set_tos
    -- Feilds={op_type,attr_list}
    -- m_role_set_tos={{required,byte},{repeated,p_attr}}
    [807]={5,"op_type",1108,"attr_list"},

    -- m_role_cure_tos
    -- Feilds={type}
    -- m_role_cure_tos={{required,byte}}
    [811]={5,"type"},

    -- m_pet_query_tos
    -- Feilds={op_type,pet_id}
    -- m_pet_query_tos={{required,byte},{optional,int64}}
    [1501]={5,"op_type",2,"pet_id"},

    -- m_pet_battle_tos
    -- Feilds={pet_id}
    -- m_pet_battle_tos={{required,int64}}
    [1502]={2,"pet_id"},

    -- m_pet_back_tos
    -- Feilds={}
    -- m_pet_back_tos={}
    [1503]={},

    -- m_pet_free_tos
    -- Feilds={pet_id,bag_type}
    -- m_pet_free_tos={{required,int64},{required,byte}}
    [1504]={2,"pet_id",5,"bag_type"},

    -- m_fight_attack_tos
    -- Feilds={skill_id,step,src_id,src_type,target_id,target_type,target_pos}
    -- m_fight_attack_tos={{required,int32},{required,byte},{required,int64},{required,byte},{required,int64},{required,byte},{required,p_pos}}
    [1401]={3,"skill_id",5,"step",2,"src_id",5,"src_type",2,"target_id",5,"target_type",105,"target_pos"},

    -- m_letter_get_tos
    -- Feilds={}
    -- m_letter_get_tos={}
    [902]={},

    -- m_letter_open_tos
    -- Feilds={letter_id}
    -- m_letter_open_tos={{required,int32}}
    [903]={3,"letter_id"},

    -- m_letter_p2p_send_tos
    -- Feilds={receiver,text,goods_id_list}
    -- m_letter_p2p_send_tos={{required,string},{required,string},{repeated,int64}}
    [901]={7,"receiver",7,"text",1002,"goods_id_list"},

    -- m_letter_delete_tos
    -- Feilds={letter_ids}
    -- m_letter_delete_tos={{repeated,int32}}
    [904]={1003,"letter_ids"},

    -- m_letter_accept_goods_tos
    -- Feilds={letter_id,goods_id}
    -- m_letter_accept_goods_tos={{required,int32},{required,int64}}
    [905]={3,"letter_id",2,"goods_id"},

    -- m_mission_query_tos
    -- Feilds={op_type,id_list}
    -- m_mission_query_tos={{required,byte},{repeated,int32}}
    [1001]={5,"op_type",1003,"id_list"},

    -- m_mission_do_tos
    -- Feilds={op_type,id,npc_id,prop_choose}
    -- m_mission_do_tos={{required,byte},{required,int32},{required,int32},{repeated,int32}}
    [1002]={5,"op_type",3,"id",3,"npc_id",1003,"prop_choose"},

    -- m_mission_do_complete_tos
    -- Feilds={id}
    -- m_mission_do_complete_tos={{required,int32}}
    [1005]={3,"id"},

    -- m_mission_do_submit_tos
    -- Feilds={big_group,do_times}
    -- m_mission_do_submit_tos={{required,int32},{required,int16}}
    [1006]={3,"big_group",4,"do_times"},

    -- m_mission_cancel_tos
    -- Feilds={id}
    -- m_mission_cancel_tos={{required,int32}}
    [1003]={3,"id"},

    -- m_mission_recolor_tos
    -- Feilds={op_type,mission_id,to_color}
    -- m_mission_recolor_tos={{required,byte},{required,int32},{optional,byte}}
    [1007]={5,"op_type",3,"mission_id",5,"to_color"},

    -- m_mission_auto_tos
    -- Feilds={op_type,big_group,loop_times}
    -- m_mission_auto_tos={{required,byte},{optional,int32},{optional,int16}}
    [1008]={5,"op_type",3,"big_group",4,"loop_times"},

    -- m_customer_service_query_tos
    -- Feilds={op_type,id}
    -- m_customer_service_query_tos={{required,byte},{required,int32}}
    [1101]={5,"op_type",3,"id"},

    -- m_customer_service_do_tos
    -- Feilds={op_type,type,title,content,id}
    -- m_customer_service_do_tos={{required,byte},{optional,byte},{optional,string},{optional,string},{optional,int32}}
    [1102]={5,"op_type",5,"type",7,"title",7,"content",3,"id"},

    -- m_customer_service_del_tos
    -- Feilds={op_type,id,del_ids}
    -- m_customer_service_del_tos={{required,byte},{optional,int32},{repeated,int32}}
    [1104]={5,"op_type",3,"id",1003,"del_ids"},

    -- m_family_query_tos
    -- Feilds={op_type,op_from,page_id,page_number,faction_id,content}
    -- m_family_query_tos={{required,byte},{required,byte},{required,int16},{required,int16},{optional,byte},{optional,string}}
    [1201]={5,"op_type",5,"op_from",4,"page_id",4,"page_number",5,"faction_id",7,"content"},

    -- m_family_get_tos
    -- Feilds={op_type,family_id}
    -- m_family_get_tos={{required,byte},{optional,int64}}
    [1213]={5,"op_type",2,"family_id"},

    -- m_family_create_tos
    -- Feilds={op_type,family_name,is_friend_invite}
    -- m_family_create_tos={{required,byte},{required,string},{required,byte}}
    [1202]={5,"op_type",7,"family_name",5,"is_friend_invite"},

    -- m_family_request_tos
    -- Feilds={family_id}
    -- m_family_request_tos={{required,int64}}
    [1203]={2,"family_id"},

    -- m_family_invite_tos
    -- Feilds={op_type,invited_role_id,src_role_id,family_id}
    -- m_family_invite_tos={{required,byte},{required,int64},{optional,int64},{optional,int64}}
    [1204]={5,"op_type",2,"invited_role_id",2,"src_role_id",2,"family_id"},

    -- m_family_accept_tos
    -- Feilds={op_type,role_id}
    -- m_family_accept_tos={{required,byte},{required,int64}}
    [1205]={5,"op_type",2,"role_id"},

    -- m_family_refuse_tos
    -- Feilds={op_type,role_id}
    -- m_family_refuse_tos={{required,byte},{optional,int64}}
    [1206]={5,"op_type",2,"role_id"},

    -- m_family_disband_tos
    -- Feilds={}
    -- m_family_disband_tos={}
    [1207]={},

    -- m_family_fire_tos
    -- Feilds={role_id}
    -- m_family_fire_tos={{required,int64}}
    [1208]={2,"role_id"},

    -- m_family_leave_tos
    -- Feilds={}
    -- m_family_leave_tos={}
    [1209]={},

    -- m_family_set_tos
    -- Feilds={op_type,family_id,role_id,value}
    -- m_family_set_tos={{required,byte},{optional,int64},{optional,int64},{optional,string}}
    [1211]={5,"op_type",2,"family_id",2,"role_id",7,"value"},

    -- m_family_turn_tos
    -- Feilds={role_id}
    -- m_family_turn_tos={{required,int64}}
    [1212]={2,"role_id"},

    -- m_ranking_get_tos
    -- Feilds={rank_id}
    -- m_ranking_get_tos={{required,int32}}
    [1301]={3,"rank_id"},

    -- m_fb_enter_tos
    -- Feilds={fb_id}
    -- m_fb_enter_tos={{required,int16}}
    [1601]={4,"fb_id"},

    -- m_fb_quit_tos
    -- Feilds={fb_id}
    -- m_fb_quit_tos={{required,int16}}
    [1602]={4,"fb_id"},

    -- m_fb_query_tos
    -- Feilds={fb_id}
    -- m_fb_query_tos={{required,int16}}
    [1603]={4,"fb_id"},

    -- m_fb_update_tos
    -- Feilds={}
    -- m_fb_update_tos={}
    [1604]={},

    -- m_fb_monster_tos
    -- Feilds={}
    -- m_fb_monster_tos={}
    [1605]={},

    -- m_chat_get_goods_tos
    -- Feilds={goods_id}
    -- m_chat_get_goods_tos={{required,int64}}
    [504]={2,"goods_id"},

    -- m_chat_in_channel_tos
    -- Feilds={channel_type,msg,msg_code,msg_type}
    -- m_chat_in_channel_tos={{optional,byte},{optional,string},{optional,int32},{optional,byte}}
    [501]={5,"channel_type",7,"msg",3,"msg_code",5,"msg_type"},

    -- m_team_create_tos
    -- Feilds={}
    -- m_team_create_tos={}
    [1801]={},

    -- m_team_invite_tos
    -- Feilds={role_id}
    -- m_team_invite_tos={{required,int64}}
    [1802]={2,"role_id"},

    -- m_team_apply_tos
    -- Feilds={role_id,team_id}
    -- m_team_apply_tos={{required,int64},{required,int32}}
    [1803]={2,"role_id",3,"team_id"},

    -- m_team_accept_tos
    -- Feilds={role_id}
    -- m_team_accept_tos={{required,int64}}
    [1804]={2,"role_id"},

    -- m_team_refuse_tos
    -- Feilds={op_code}
    -- m_team_refuse_tos={{required,int32}}
    [1805]={3,"op_code"},

    -- m_team_leave_tos
    -- Feilds={}
    -- m_team_leave_tos={}
    [1806]={},

    -- m_team_kick_tos
    -- Feilds={role_id}
    -- m_team_kick_tos={{required,int64}}
    [1807]={2,"role_id"},

    -- m_team_disband_tos
    -- Feilds={}
    -- m_team_disband_tos={}
    [1808]={},

    -- m_team_appoint_tos
    -- Feilds={role_id}
    -- m_team_appoint_tos={{required,int64}}
    [1809]={2,"role_id"}
}

return tos_defines