%% -*- coding: latin-1 -*-
%% Author: caochuncheng2002@gmail.com
%% Created: 2013-11-25
%% Description: 地图配置接口模块
%% This file is generated by script tool,Do not edit it.

-module(cfg_map).


-include("common_records.hrl").

-export([
         get_map_info/1,
         get_map_bron_point/1,
         get_map_ref/1,
         get_map_monster/1,
         get_map_jump/1,
         get_slice_name/1,

         get_all_map_id/0
        ]).

%% 获取地图可走点
get_map_ref(MapId) ->
  case get_map_info(MapId) of
      [#r_map_info{mcm_module=McmModule}] ->
          McmModule:get_map_bron_point(MapId);
      _ ->
          []
  end.

%% 获取怪物配置
get_map_monster(MapId) ->
  case get_map_info(MapId) of
      [#r_map_info{mcm_module=McmModule}] ->
          McmModule:get_map_monster(MapId);
      _ ->
          []
  end.

%% 获取跳转点
get_map_jump({MapId,Tx,Ty}) ->
  case get_map_info(MapId) of
      [#r_map_info{mcm_module=McmModule}] ->
          McmModule:get_map_jump({MapId,Tx,Ty});
      _ ->
          []
  end.

%% 获取 Slice Info
get_slice_name({MapId,Tx,Ty}) ->
  case get_map_info(MapId) of
      [#r_map_info{mcm_module=McmModule}] ->
          McmModule:get_slice_name({Tx,Ty});
      _ ->
          []
  end.

get_map_bron_point(20002) ->
    [{2183,7183}];
get_map_bron_point(20001) ->
    [{4597,2004}];
get_map_bron_point(10002) ->
    [{2183,7183}];
get_map_bron_point(10001) ->
    [{6850,4618}];
%% 获取地图出生点信息
get_map_bron_point(_MapId) ->
  [].

get_map_info(20002) ->
    [{r_map_info,20002,<<"副本2">>,1,0,0,0,0,0,3500,7800,0,1,cfg_mcm_20002}];
get_map_info(20001) ->
    [{r_map_info,20001,<<"遗迹深处">>,1,0,0,0,0,0,5300,3000,0,1,cfg_mcm_20001}];
get_map_info(10002) ->
    [{r_map_info,10002,<<"主城2">>,0,0,0,0,0,0,3500,7800,0,1,cfg_mcm_10002}];
get_map_info(10001) ->
    [{r_map_info,10001,<<"浮空遗迹">>,0,0,0,0,0,0,7400,7200,0,1,cfg_mcm_10001}];
%% 获取地图配置信息
get_map_info(_MapId) ->
  [].

%% 获取所有地图Id
get_all_map_id() ->
    [20002,
     20001,
     10002,
     10001].

