%% -*- coding: latin-1 -*-
%% Author: caochuncheng2002@gmail.com
%% Created: 2015-09-18
%% Description: NPC配置
%% This file is generated by script tool,Do not edit it.

-module(cfg_npc).


-export([
         find/1
        ]).

find(1) ->
    [{r_map_res,10001,4,1,4160,6149,0,undefined}];
find(_) ->
    [].

