%% -*- coding: latin-1 -*-
%% Author: caochuncheng2002@gmail.com
%% Created: 2013-11-25
%% Description: 地图字典信息
%% This file is generated by script tool,Do not edit it.

-module(cfg_map_dict).


-export([
         get_map_dict/0
        ]).

get_map_dict() ->
    "[{\"map_id\":20002,\"name\":\"副本2\",\"type\":1,\"sub_type\":0,\"faction_id\":0},
      {\"map_id\":20001,\"name\":\"遗迹深处\",\"type\":1,\"sub_type\":0,\"faction_id\":0},
      {\"map_id\":10002,\"name\":\"主城2\",\"type\":0,\"sub_type\":0,\"faction_id\":0},
      {\"map_id\":10001,\"name\":\"浮空遗迹\",\"type\":0,\"sub_type\":0,\"faction_id\":0}]".

