%%%-------------------------------------------------------------------
%%% @author fancy
%%% @copyright (C) 2015, <COMPANY>
%%% @doc
%%%
%%% @end
%%% Created : 06. 八月 2015 下午4:07
%%%-------------------------------------------------------------------
-module(player_pack).
-author("fancy").
-include("server.hrl").
-include("common.hrl").
-include("goods.hrl").
-include("scene.hrl").
%% API
-export([
    trans13001/1,
    trans13002/1,
    trans13014/2,
    trans13013/2,
    trans13041/2
]).

trans13001(Player) ->
    #player{
        key = Key,
        sn = Sn,
        sn_cur = SnCur,
        sn_name = SnName,
        pf = Pf,
        nickname = Nickname,
        lv = Lv,
        scene = Scene,
        copy = Copy,
        x = X,
        y = Y,
        career = Career,
        new_career = NewCareer,
        sex = Sex,
        realm = Realm,
        exp_lim = ExpLim,
        exp = Exp,
        manor_pt = ManorPt,
        equip_part = EquipPart,
        act_gold = ActGold,
        fairy_crystal = FairyCrystal,
        vip_lv = VipLv,
        vip_state = VipState,
        guild = Guild,
        gold = Gold,
        bgold = Bgold,
        coin = Coin,
        bcoin = Bcoin,
        honor = Honor,
        arena_pt = ArenaPt,
        xingyun_pt = Star_Pt,
        pk = PkSt,
        evil = PEvil,
        team_key = TeamKey,
        convoy_state = ConvoyState,
        design = DesList,
        pet = #fpet{
            type_id = PetTypeId,
            figure = PetFigure,
            name = PetName
        },
        baby = #fbaby{
            type_id = BabyTypeId,
            figure = BabyFigure,
            name = BabyName
        },
        mount_id = MountId,
        wing_id = Wing,
        baby_wing_id = BabyWingId,
        baby_mount_id = BabyMountId,
        baby_weapon_id = BabyWeaponId,
        equip_figure = #equip_figure{
            weapon_id = WeaponId,
            clothing_id = ClothingId
        },
        light_weaponid = LightEeaponid,
        sprite_lv = Sprite_lv,
        fashion = #fashion_figure{
            fashion_cloth_id = FashionCloth_id,
            fashion_head_id = FashionHeadId,
            fashion_decoration_id = DecorationId
        },
        xinghun = Xinghun,
        figure = Figure,
        group = Group,
        bf_score = BfScore,
        combo = Combo,
        scene_face = SceneFace,
        reg_time = RegTime,
        avatar = Avatar,
        crown = Crown,
        sword_pool_figure = SwordPoolFigure,
        magic_weapon_id = MagicWeaponId,
        god_weapon_id = GodWeaponId,
        god_weapon_skill = GodWeaponSkill,
        reiki = Reiki,
        sd_pt = SdPt,
        exploit_pri = ExploitPri,
        repute = Repute,
        charm = Charm,
        pet_weaponid = PetWeaponId,
        footprint_id = FootprintId,
        is_view = IsView,
        world_lv = Wlv,
        world_lv_add = WlvAdd,
        cat_id = CatId,
        golden_body_id = GoldenBodyId,
        god_treasure_id = GodTreasureId,
        jade_id = JadeId,
        marry = Marry,
        sweet = Sweet,
        sit_state = SitState,
        show_golden_body = ShowGoldenBody,
        war_team = WarTeam,
        d_vip = #dvip{
            vip_type = VipType,
            time = EndTime
        },
        wear_element_list = WearElementList
    } = Player,
    Now = util:unixtime(),
    GuildKey = Guild#st_guild.guild_key,
    GuildName = Guild#st_guild.guild_name,
    GuildPos = Guild#st_guild.guild_position,
    #pk{
        pk = Pkstate,
        value = Pkvalue,
        chivalry = PkChivalry,
        kill_count = PkKillcount,
        protect_time = PkProtectTime
    } = PkSt,
    PkProtectTime1 = max(0, PkProtectTime - Now),
    IsEvil = PEvil#pevil.evil,
    LeaveEvilTime = max(0, PEvil#pevil.evil_time - Now),
    DesignList = DesList,
    AttList = trans13002(Player),
    Line = ?IF_ELSE(is_integer(Copy), Copy, 0),
    StrengthLv = Player#player.max_stren_lv,
    StoneLv = Player#player.max_stone_lv,
    Exploit = 0,
    NewWlvAdd = round(WlvAdd * 100),
    MarryType = Marry#marry.marry_type,
    CoupleName = Marry#marry.couple_name,
    CoupleSex = Marry#marry.couple_sex,
    CruiseState = Marry#marry.cruise_state,
    CouplePkey = Marry#marry.couple_key,
    MyRingLv = marry_ring:get_my_ring_lv(),
    MarryRingType = marry_ring:get_my_ring_type(Player),
    CoupleRingLv = marry_ring:get_couple_lv(Player),
    LeftTime = max(EndTime - util:unixtime(), 0),
    SkillEffect = Player#player.skill_effect,
    XianOpenLv = data_menu_open:get(71),
    XianStage = ?IF_ELSE(Player#player.lv < XianOpenLv, 0, Player#player.xian_stage),
    JiandaoOpenLv = data_menu_open:get(90),
    JiandaoStage = ?IF_ELSE(Player#player.lv < JiandaoOpenLv, 0, Player#player.jiandao_stage),
    NewWearElementList = util:list_tuple_to_list(WearElementList),
    {
        Key, Sn, SnCur, SnName, Pf, Nickname, Lv, Scene, Line, X, Y,
        Career, Sex, Realm, ExpLim, Exp, Gold, Bgold, Coin, Bcoin, Exploit,
        Honor, Reiki, SdPt, ExploitPri, Repute, Charm, ArenaPt, Star_Pt, Xinghun, GuildKey,
        GuildName, GuildPos, ManorPt, EquipPart, ActGold,FairyCrystal, VipLv, VipState, Sweet, MountId, Pkstate, Pkvalue, IsEvil, LeaveEvilTime, PetTypeId, PetFigure,
        PetName, TeamKey, Wing, WeaponId, ClothingId, LightEeaponid, FashionCloth_id, FootprintId, DesignList, StrengthLv,
        StoneLv, AttList, ConvoyState, Figure, Group, BfScore, Combo, SceneFace, Sprite_lv, RegTime,
        Avatar, Crown, SwordPoolFigure, MagicWeaponId, GodWeaponId, GodWeaponSkill, FashionHeadId, PkKillcount, PkChivalry, PetWeaponId,
        PkProtectTime1, IsView, Wlv, NewWlvAdd, CatId, MarryType, CoupleName, CoupleSex, CruiseState, GoldenBodyId, JadeId, GodTreasureId,
        CouplePkey, MyRingLv, SitState, DecorationId, MarryRingType, CoupleRingLv, BabyTypeId, BabyFigure, BabyName, BabyWingId, NewCareer,
        VipType, LeftTime, BabyMountId, BabyWeaponId, SkillEffect, XianStage, ShowGoldenBody, WarTeam#st_war_team.war_team_key, WarTeam#st_war_team.war_team_name, WarTeam#st_war_team.war_team_position,
        JiandaoStage, NewWearElementList
    }.

trans13002(Player) ->
    Attribute1 = ?IF_ELSE(Player#player.scene == ?SCENE_ID_CROSS_SCUFFLE, Player#player.scuffle_attribute, Player#player.attribute),
    Attribute = ?IF_ELSE(Player#player.scene == ?SCENE_ID_CROSS_SCUFFLE_ELITE, Player#player.scuffle_elite_attribute, Attribute1),
    #attribute{
        hp_lim = Hplim,
        mp_lim = Mplim,
        att = Att,
        def = Def,
        att_area = AttArea,
        speed = Speed,
        att_speed = AttSpeed,
        prepare = Prepare,
        dodge = Dodge,
        hit = Hit,
        crit = Crit,
        ten = Ten,
        crit_inc = CritInc,
        crit_dec = CritDec,
        hurt_inc = HurtInc,
        hurt_dec = HurtDec,
        hurt_fix = HurtFix,
        crit_ratio = CritRatio,
        hit_ratio = HitRatio,
        hp_lim_inc = HpLimInc,
        recover = Recover,
        recover_hit = RecoverHit,
        size = Size,
        cure = Cure,
        pvp_inc = PvpInc,
        pvp_dec = PvpDec
    } = Attribute,
    Hp = Player#player.hp,
    Mp = Player#player.mp,
    Combatpower = Player#player.cbp,
    [Hplim, Hp, Mplim, Mp, Att, Def, AttArea, Speed, AttSpeed, Prepare,
        Dodge, Hit, Crit, Ten, CritInc, CritDec, HurtInc, HurtDec, HurtFix, CritRatio, HitRatio, HpLimInc,
        Recover, RecoverHit, Size, Cure, Combatpower, PvpInc, PvpDec].

trans13013(Player, Sn) ->
    Pkey = Player#player.key,
    P0_name = Player#player.nickname,
    P0_lv = Player#player.lv,
    P0_career = Player#player.career,
    P0_new_career = Player#player.new_career,
    P0_sex = Player#player.sex,
    P0_guildname = Player#player.guild#st_guild.guild_name,
    P0_viplv = Player#player.vip_lv,
    P0_fighting_capacity = Player#player.cbp,
    P0_mount_id = Player#player.mount_id,
    P0_wing_id = Player#player.wing_id,
    P0_wepon_id = Player#player.equip_figure#equip_figure.weapon_id,
    P0_clothing_id = Player#player.equip_figure#equip_figure.clothing_id,
    P0_light_wepon_id = Player#player.light_weaponid,
    P0_fashion_cloth_id = Player#player.fashion#fashion_figure.fashion_cloth_id,
    P0_footprint_id = Player#player.footprint_id,
    StrengLv = Player#player.max_stren_lv,
    StoneLv = Player#player.max_stone_lv,
    MarryRingLv = Player#player.marry_ring_lv,
    MarryRingType = Player#player.marry_ring_type,
    GoodsList = ?IF_ELSE(is_list(Player#player.weared_equip), [[WearedEquip#equip_attr_view.goods_id, WearedEquip#equip_attr_view.stren, WearedEquip#equip_attr_view.star, WearedEquip#equip_attr_view.god_forging, WearedEquip#equip_attr_view.level, [[attribute_util:attr_tans_client(K), V] || {K, V} <- WearedEquip#equip_attr_view.wash], [[K, V] || {K, V} <- WearedEquip#equip_attr_view.gem], WearedEquip#equip_attr_view.magic_info] || WearedEquip <- Player#player.weared_equip, is_record(WearedEquip, equip_attr_view)], []),

    DesignList = ?IF_ELSE(is_list(Player#player.design), Player#player.design, []),
    PetTypeId = Player#player.pet#fpet.type_id,
    PetName = Player#player.pet#fpet.name,
    PetFigureId = Player#player.pet#fpet.figure,
    AttrDanList = [[GoodsId, NUm] || {GoodsId, NUm} <- Player#player.attr_dan],
    Avatar = Player#player.avatar,
    AttrListss = trans13002(Player),
    HeadId = Player#player.fashion#fashion_figure.fashion_head_id,
    ErrorCode = ?IF_ELSE(Player#player.cbp =:= 0, 4, 1),
    P0_pet_weapon_id = Player#player.pet_weaponid,
    P0_exp = Player#player.exp,
    ExpLim = data_exp:get(P0_lv),
    Evil = Player#player.pk#pk.value,
    P0_charm = Player#player.charm,
    P0_CatId = Player#player.cat_id,
    P0_GoldenBodyId = Player#player.golden_body_id,
    P0_GodTreasureId = Player#player.god_treasure_id,
    P0_JadeId = Player#player.jade_id,
    CoupleName = Player#player.marry#marry.couple_name,
    CoupleMarryRingLv = 0,
    %%[StAch#st_achieve.lv, StAch#st_achieve.score, ScoreLim, StAch#st_achieve.score_list].
    [AchLv, AchScore, AchScoreLim, AchList] = Player#player.achieve_view,
    BabyTypeId = Player#player.baby#fbaby.type_id,
    BabyName = Player#player.baby#fbaby.name,
    BabyFigureId = Player#player.baby#fbaby.figure,
    #dvip{vip_type = VipType, time = EndTime} = Player#player.d_vip,
    LeftTime = max(EndTime - util:unixtime(), 0),
    {
        ErrorCode, Sn, Pkey, AttrListss, P0_name,
        P0_lv, P0_career, P0_sex, P0_guildname, P0_viplv,
        P0_fighting_capacity, P0_mount_id, P0_wing_id, P0_wepon_id, P0_clothing_id,
        P0_light_wepon_id, P0_fashion_cloth_id, P0_footprint_id, DesignList,
        GoodsList, StrengLv, StoneLv, PetTypeId, PetName,
        PetFigureId, AttrDanList, Avatar, HeadId, P0_pet_weapon_id,
        ExpLim, P0_exp, P0_charm, Evil, AchLv,
        AchScore, AchScoreLim, AchList, P0_CatId, P0_GoldenBodyId, P0_JadeId, P0_GodTreasureId,
        MarryRingLv, MarryRingType, CoupleName, CoupleMarryRingLv
        , BabyTypeId, BabyFigureId, BabyName, P0_new_career, VipType, LeftTime
    }.

trans13041(Player, Sn) ->
    BabyTypeId = Player#player.baby#fbaby.type_id,
    BabyName = Player#player.baby#fbaby.name,
    BabyFigureId = Player#player.baby#fbaby.figure,
    BabyStep = Player#player.baby#fbaby.step,
    BabyLv = Player#player.baby#fbaby.lv,
    Attr = Player#player.baby#fbaby.att,
    SkillList = Player#player.baby#fbaby.skill,
    PackSkillList = baby:pack_baby_skill_13041(BabyTypeId, BabyStep, SkillList),
    ?DEBUG("PackSkillList ~p~n", [PackSkillList]),
    GoodsList =
        ?IF_ELSE(is_list(Player#player.baby_equip),
            [[
                WearedEquip#baby_equip_attr_view.goods_id,
                WearedEquip#baby_equip_attr_view.color,
                WearedEquip#baby_equip_attr_view.sex,
                WearedEquip#baby_equip_attr_view.cbp,
                [[attribute_util:attr_tans_client(Type), Value] || {Type, Value} <- WearedEquip#baby_equip_attr_view.fix_attrs],
                [[attribute_util:attr_tans_client(Type), Value] || {Type, Value} <- WearedEquip#baby_equip_attr_view.random_attrs]
            ] || WearedEquip <- Player#player.baby_equip, is_record(WearedEquip, baby_equip_attr_view)],
            []),
    Q = {
        Player#player.key,
        Sn,
        BabyTypeId,
        BabyFigureId,
        BabyName,
        BabyStep,
        BabyLv,
        PackSkillList,
        attribute_util:pack_attr(Attr),
        GoodsList
    },
    ?DEBUG("Q ~p~n", [Q]),
    Q.

trans13014(Player, Sn) ->
    {
        Sn,
        Player#player.key,
        Player#player.nickname,
        Player#player.career,
        Player#player.sex,
        Player#player.vip_lv,
        Player#player.wing_id,
        Player#player.equip_figure#equip_figure.weapon_id,
        Player#player.equip_figure#equip_figure.clothing_id,
        Player#player.light_weaponid,
        Player#player.fashion#fashion_figure.fashion_cloth_id,
        Player#player.pet#fpet.type_id,
        Player#player.pet#fpet.figure,
        Player#player.pet#fpet.name,
        Player#player.fashion#fashion_figure.fashion_head_id,
        Player#player.pet_weaponid,
        Player#player.cat_id,
        Player#player.golden_body_id,
        Player#player.god_treasure_id,
        Player#player.jade_id,
        Player#player.baby#fbaby.type_id,
        Player#player.baby#fbaby.figure,
        Player#player.baby#fbaby.name,
        Player#player.d_vip#dvip.vip_type,
        Player#player.d_vip#dvip.time
    }.

